install:
 - sudo apt-get update
 - sudo apt-get install haskell-platform autoconf libtool make ncurses-dev g++ dblatex docbook-xsl docbook-utils
 - ./sync-all -r git://github.com/ghc --testsuite --no-dph get
script:
 - cabal update
 - cabal install happy alex
 - PATH=~/.cabal/bin:$PATH CPUS=3 ./validate --fast --no-dph
