install:
 - sudo apt-get update
 - sudo apt-get install haskell-platform autoconf libtool make ncurses-dev g++ dblatex docbook-xsl docbook-utils
 - ./sync-all -r git://github.com/ghc --testsuite --no-dph get
script:
 - set e
 - cabal update
 - cabal install happy alex
 - echo 'V = 0' >> mk/build.mk # otherwise we hit log file limits on travis.
# The quick settings:
 - echo 'SRC_HC_OPTS        = -H64m -O0 -fasm' >> mk/build.mk
 - echo 'GhcStage1HcOpts    = -O -fasm' >> mk/build.mk
 - echo 'GhcStage2HcOpts    = -O0 -fasm -Wall' >> mk/build.mk
 - echo 'GhcLibHcOpts       = -O -fasm' >> mk/build.mk
 - echo 'SplitObjs          = NO' >> mk/build.mk
 - echo 'HADDOCK_DOCS       = NO' >> mk/build.mk
 - echo 'BUILD_DOCBOOK_HTML = NO' >> mk/build.mk
 - echo 'BUILD_DOCBOOK_PS   = NO' >> mk/build.mk
 - echo 'BUILD_DOCBOOK_PDF  = NO' >> mk/build.mk
 - echo 'DYNAMIC_GHC_PROGRAMS = NO' >> mk/build.mk
 - echo 'GhcLibWays = v'          >> mk/build.mk
# Lets do it
 - perl boot
 - PATH=~/.cabal/bin:$PATH ./configure 
 - PATH=~/.cabal/bin:$PATH make -j3
 - PATH=~/.cabal/bin:$PATH make -C testsuite fast THREADS=3 VERBOSE=2 SKIP_PERF_TESTS=YES
