install:
 - sudo apt-get update
 - sudo apt-get install haskell-platform autoconf libtool make ncurses-dev g++ dblatex docbook-xsl docbook-utils
 - ./sync-all -r git://github.com/ghc --testsuite --no-dph get
script:
 - cabal update
 - cabal install happy alex
 - echo 'V = 0' > mk/validate.mk # otherwise we hit log file limits on travis.
 - PATH=~/.cabal/bin:$PATH ./validate --no-dph --fast
