install:
 - sudo apt-get update
 - sudo apt-get install haskell-platform autoconf libtool make ncurses-dev g++ dblatex docbook-xsl docbook-utils
 - ./sync-all --testsuite --no-dph get
script:
 - CPUS=3 ./validate --fast --no-dph

